[build]
  command = "yarn install && yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://smother-server-35b3f9ca479c.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
